using System.Text.Json;
using DocumentProcessing.Contracts.Messages;
using DocumentProcessing.Contracts.Models;

namespace DocumentProcessing.Tests.Contracts;

public class DocumentEventTests
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    // ── EventType ──────────────────────────────────────────────────

    [Fact]
    public void EventType_ReturnsClassName_ForAllMessageTypes()
    {
        var uploaded = new DocumentUploaded { Document = CreateMetadata() };
        Assert.Equal("DocumentUploaded", uploaded.EventType);

        var classified = new DocumentClassified { Document = CreateMetadata(), Confidence = 0.9 };
        Assert.Equal("DocumentClassified", classified.EventType);

        var extracted = new DocumentContentExtracted { Document = CreateMetadata(), PageCount = 1 };
        Assert.Equal("DocumentContentExtracted", extracted.EventType);

        var enriched = new DocumentMetadataEnriched { Document = CreateMetadata() };
        Assert.Equal("DocumentMetadataEnriched", enriched.EventType);

        var approved = new DocumentApproved { Document = CreateMetadata() };
        Assert.Equal("DocumentApproved", approved.EventType);

        var rejected = new DocumentRejected { Document = CreateMetadata() };
        Assert.Equal("DocumentRejected", rejected.EventType);
    }

    // ── CorrelationId ──────────────────────────────────────────────

    [Fact]
    public void CorrelationId_IsAutoGenerated()
    {
        var a = new DocumentUploaded { Document = CreateMetadata() };
        var b = new DocumentUploaded { Document = CreateMetadata() };
        Assert.NotEqual(a.CorrelationId, b.CorrelationId);
        Assert.True(Guid.TryParse(a.CorrelationId, out _));
        Assert.True(Guid.TryParse(b.CorrelationId, out _));
    }

    [Fact]
    public void CorrelationId_IsPreservable_DuringChaining()
    {
        var evt = new DocumentUploaded
        {
            CorrelationId = "550e8400-e29b-41d4-a716-446655440000",
            Document = CreateMetadata()
        };
        Assert.Equal("550e8400-e29b-41d4-a716-446655440000", evt.CorrelationId);
    }

    // ── OccurredAt ─────────────────────────────────────────────────

    [Fact]
    public void OccurredAt_IsSetToUtcNow_Approximately()
    {
        var before = DateTimeOffset.UtcNow;
        var evt = new DocumentUploaded { Document = CreateMetadata() };
        var after = DateTimeOffset.UtcNow;

        Assert.InRange(evt.OccurredAt, before.AddSeconds(-5), after.AddSeconds(5));
    }

    // ── DocumentUploaded ─────────────────────────────────────────────

    [Fact]
    public void DocumentUploaded_StatusIsSet_ByCaller()
    {
        // The caller is responsible for setting Status to Uploaded.
        // The IngestDocument function does this explicitly.
        var metadata = new DocumentMetadata
        {
            Status = DocumentStatus.Uploaded
        };

        var evt = new DocumentUploaded { Document = metadata };

        Assert.Equal(DocumentStatus.Uploaded, evt.Document.Status);
    }

    [Fact]
    public void DocumentUploaded_IsSimpleRecord_InheritingDocumentEvent()
    {
        var metadata = new DocumentMetadata { FileName = "test.pdf" };
        var evt = new DocumentUploaded
        {
            CorrelationId = "cid-001",
            Document = metadata
        };

        Assert.Equal("cid-001", evt.CorrelationId);
        Assert.Equal(metadata, evt.Document);
        Assert.Equal("DocumentUploaded", evt.EventType);
    }

    // ── Message property round-trips ───────────────────────────────

    [Fact]
    public void DocumentClassified_HasConfidenceProperty()
    {
        var evt = new DocumentClassified
        {
            Document = CreateMetadata(),
            Confidence = 0.95
        };
        Assert.Equal(0.95, evt.Confidence);
    }

    [Fact]
    public void DocumentContentExtracted_HasPageCountAndProcessingDuration()
    {
        var duration = TimeSpan.FromSeconds(3.5);
        var evt = new DocumentContentExtracted
        {
            Document = CreateMetadata(),
            PageCount = 12,
            ProcessingDuration = duration
        };
        Assert.Equal(12, evt.PageCount);
        Assert.Equal(duration, evt.ProcessingDuration);
    }

    [Fact]
    public void DocumentMetadataEnriched_HasEnrichedFieldCount()
    {
        var evt = new DocumentMetadataEnriched
        {
            Document = CreateMetadata(),
            EnrichedFieldCount = 7
        };
        Assert.Equal(7, evt.EnrichedFieldCount);
    }

    [Fact]
    public void DocumentApproved_HasNullableArchivePath()
    {
        var withoutPath = new DocumentApproved { Document = CreateMetadata() };
        Assert.Null(withoutPath.ArchivePath);

        var withPath = new DocumentApproved
        {
            Document = CreateMetadata(),
            ArchivePath = "/archive/compliance/invoice-001.pdf"
        };
        Assert.Equal("/archive/compliance/invoice-001.pdf", withPath.ArchivePath);
    }

    [Fact]
    public void DocumentRejected_HasNullableRejectionReason()
    {
        var withoutReason = new DocumentRejected { Document = CreateMetadata() };
        Assert.Null(withoutReason.RejectionReason);

        var withReason = new DocumentRejected
        {
            Document = CreateMetadata(),
            RejectionReason = "Missing required fields"
        };
        Assert.Equal("Missing required fields", withReason.RejectionReason);
    }

    // ── JSON serialization round-trip ──────────────────────────────

    [Fact]
    public void DocumentUploaded_RoundTripsJson()
    {
        var evt = new DocumentUploaded
        {
            CorrelationId = "corr-123",
            Document = new DocumentMetadata
            {
                DocumentId = "doc-456",
                FileName = "test.pdf",
                ContentType = "application/pdf",
                FileSizeBytes = 1024,
                BlobUri = "https://example.com/test.pdf",
                UploadedBy = "alice",
                UploadedAt = new DateTimeOffset(2026, 6, 3, 12, 0, 0, TimeSpan.Zero)
            }
        };

        var json = JsonSerializer.Serialize(evt, JsonOptions);
        var deserialized = JsonSerializer.Deserialize<DocumentUploaded>(json, JsonOptions);

        Assert.NotNull(deserialized);
        Assert.Equal(evt.CorrelationId, deserialized!.CorrelationId);
        Assert.Equal(evt.Document.DocumentId, deserialized.Document.DocumentId);
        Assert.Equal(evt.Document.FileName, deserialized.Document.FileName);
        Assert.Equal("DocumentUploaded", deserialized.EventType);
    }

    // ── Helpers ────────────────────────────────────────────────────

    private static DocumentMetadata CreateMetadata()
    {
        return new DocumentMetadata
        {
            DocumentId = Guid.NewGuid().ToString("D"),
            FileName = "test.pdf",
            ContentType = "application/pdf",
            BlobUri = "https://example.com/test.pdf",
            UploadedBy = "test-user",
            UploadedAt = DateTimeOffset.UtcNow
        };
    }
}
